# This compose file is used for local development only
# It is not used in production
services:
  api:
    build: .
    command: sh -c "yarn && yarn start:dev"
    ports:
      - '${API_PORT}:${API_PORT}'
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_USER: ${MYSQL_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_DB_PASS}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - $MYSQL_DB_LOCAL_PORT:3306
    volumes:
      - mysql-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASS}
    ports:
      - $MONGO_DB_LOCAL_PORT:27017
    volumes:
      - mongo-db-data:/data/db
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  mysql-db-data: {}
  mongo-db-data: {}