# This compose file is used for local development only
# It is not used in production
services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_DB_PASS}'
      MYSQL_USER: ${MYSQL_DB_USER}
      MYSQL_PASSWORD: '${MYSQL_DB_PASS}'
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    ports:
      - $MYSQL_DB_LOCAL_PORT:3306
    networks:
      - app_network
    volumes:
      - mysql-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - $MONGO_DB_LOCAL_PORT:27017
    networks:
      - app_network
    volumes:
      - mongo-db-data:/data/db
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s

  api:
    build: .
    command: sh -c "yarn && yarn prisma:generate && yarn start:dev"
    ports:
      - '${API_PORT}:${API_PORT}'
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - app_network
    depends_on:
      mysqldb:
        condition: service_healthy
      mongodb:
        condition: service_healthy
  web:
    build:
      context: ./ui
    ports:
      - '3000:3000'
    volumes:
      - .:/app/ui
    env_file:
      - ./ui/.env
    networks:
      - app_network
    depends_on:
      - api

networks:
  app_network:
    driver: bridge

volumes:
  mysql-db-data: {}
  mongo-db-data: {}